const initialMovies = [
  { title: "Inception", genre: "Fantascienza", year: 2010 },
  { title: "Il Padrino", genre: "Thriller", year: 1972 },
  { title: "Titanic", genre: "Romantico", year: 1997 },
  { title: "Batman", genre: "Azione", year: 1989 },
  { title: "Interstellar", genre: "Fantascienza", year: 2014 },
  { title: "Pulp Fiction", genre: "Thriller", year: 1994 },
  { title: "Barry Lyndon", genre: "Storico", year: 1975 },
  { title: "Se7en", genre: "Thriller", year: 1995 },
  { title: "Fight Club", genre: "Thriller", year: 1999 },
  { title: "Shutter Island", genre: "Thriller", year: 2010 },
  { title: "The Prestige", genre: "Thriller", year: 2006 },
  { title: "Oldboy", genre: "Thriller", year: 2003 },
  { title: "Il Sesto Senso", genre: "Thriller", year: 1999 },
  { title: "The Others", genre: "Thriller", year: 2001 },
  { title: "Zodiac", genre: "Thriller", year: 2007 },
  { title: "Gone Girl", genre: "Thriller", year: 2014 },
  { title: "Prisoners", genre: "Thriller", year: 2013 },
  { title: "Mystic River", genre: "Thriller", year: 2003 },
  { title: "Die Hard", genre: "Azione", year: 1988 },
  { title: "Terminator", genre: "Azione", year: 1984 },
  { title: "Terminator 2: Il Giorno del Giudizio", genre: "Azione", year: 1991 },
  { title: "Mad Max: Fury Road", genre: "Azione", year: 2015 },
  { title: "John Wick", genre: "Azione", year: 2014 },
  { title: "John Wick 2", genre: "Azione", year: 2017 },
  { title: "John Wick 3", genre: "Azione", year: 2019 },
  { title: "Gladiatore", genre: "Azione", year: 2000 },
  { title: "300", genre: "Azione", year: 2006 },
  { title: "Matrix Reloaded", genre: "Azione", year: 2003 },
  { title: "Schindler’s List", genre: "Storico", year: 1993 },
  { title: "Il Pianista", genre: "Storico", year: 2002 },
  { title: "Braveheart", genre: "Storico", year: 1995 },
  { title: "Salvate il Soldato Ryan", genre: "Storico", year: 1998 },
  { title: "Dunkirk", genre: "Storico", year: 2017 },
  { title: "Forrest Gump", genre: "Drammatico", year: 1994 },
  { title: "Cast Away", genre: "Drammatico", year: 2000 },
  { title: "The Truman Show", genre: "Drammatico", year: 1998 },
  { title: "American Beauty", genre: "Drammatico", year: 1999 },
  { title: "Joker", genre: "Drammatico", year: 2019 },
  { title: "Requiem for a Dream", genre: "Drammatico", year: 2000 },
  { title: "Whiplash", genre: "Drammatico", year: 2014 },
  { title: "The Wolf of Wall Street", genre: "Drammatico", year: 2013 },
  { title: "Parasite", genre: "Drammatico", year: 2019 },
  { title: "C’era una volta a Hollywood", genre: "Drammatico", year: 2019 },
  { title: "Gran Torino", genre: "Drammatico", year: 2008 },
  { title: "Million Dollar Baby", genre: "Drammatico", year: 2004 },
  { title: "The Green Mile", genre: "Drammatico", year: 1999 },
  { title: "The Departed", genre: "Thriller", year: 2006 },
  { title: "Taxi Driver", genre: "Drammatico", year: 1976 },
  { title: "Goodfellas", genre: "Thriller", year: 1990 },
  { title: "Casino", genre: "Thriller", year: 1995 },
  { title: "C’era una volta in America", genre: "Storico", year: 1984 },
  { title: "Raging Bull", genre: "Drammatico", year: 1980 },
  { title: "Il Gladiatore", genre: "Storico", year: 2000 },
  { title: "Lincoln", genre: "Storico", year: 2012 },
  { title: "La Battaglia di Hacksaw Ridge", genre: "Storico", year: 2016 },
  { title: "Apollo 13", genre: "Storico", year: 1995 },
  { title: "Argo", genre: "Storico", year: 2012 },
  { title: "Le Crociate", genre: "Storico", year: 2005 },
  { title: "Troy", genre: "Storico", year: 2004 },
  { title: "Alexander", genre: "Storico", year: 2004 },
  { title: "Il Patriota", genre: "Storico", year: 2000 },
  { title: "La Passione di Cristo", genre: "Storico", year: 2004 },
  { title: "Matrix Revolutions", genre: "Azione", year: 2003 },
  { title: "The Dark Knight", genre: "Azione", year: 2008 },
  { title: "The Dark Knight Rises", genre: "Azione", year: 2012 },
  { title: "Man of Steel", genre: "Azione", year: 2013 },
  { title: "Avengers", genre: "Azione", year: 2012 },
  { title: "Avengers: Infinity War", genre: "Azione", year: 2018 },
  { title: "Avengers: Endgame", genre: "Azione", year: 2019 },
  { title: "Iron Man", genre: "Azione", year: 2008 },
  { title: "Iron Man 2", genre: "Azione", year: 2010 },
  { title: "Iron Man 3", genre: "Azione", year: 2013 },
  { title: "Captain America: Civil War", genre: "Azione", year: 2016 },
  { title: "Thor: Ragnarok", genre: "Azione", year: 2017 },
  { title: "Black Panther", genre: "Azione", year: 2018 },
  { title: "Guardiani della Galassia", genre: "Azione", year: 2014 },
  { title: "Guardiani della Galassia Vol.2", genre: "Azione", year: 2017 },
  { title: "Doctor Strange", genre: "Azione", year: 2016 },
  { title: "La La Land", genre: "Romantico", year: 2016 },
  { title: "Notting Hill", genre: "Romantico", year: 1999 },
  { title: "Pretty Woman", genre: "Romantico", year: 1990 },
  { title: "Orgoglio e Pregiudizio", genre: "Romantico", year: 2005 },
  { title: "Colpa delle Stelle", genre: "Romantico", year: 2014 },
  { title: "Romeo + Giulietta", genre: "Romantico", year: 1996 },
  { title: "Moulin Rouge!", genre: "Romantico", year: 2001 },
  { title: "Dirty Dancing", genre: "Romantico", year: 1987 },
  { title: "A Star is Born", genre: "Romantico", year: 2018 },
  { title: "Ghost", genre: "Romantico", year: 1990 },
  { title: "Il Diario di Bridget Jones", genre: "Romantico", year: 2001 },
  { title: "C’è Posta per Te", genre: "Romantico", year: 2000 },
  { title: "Se Solo Fosse Vero", genre: "Romantico", year: 2005 },
  { title: "Lettere a Juliette", genre: "Romantico", year: 2010 },
  { title: "Il Silenzio degli Innocenti", genre: "Thriller", year: 1991 },
  { title: "Memento", genre: "Thriller", year: 2000 },
  { title: "Nightcrawler", genre: "Thriller", year: 2014 },
  { title: "Heat - La Sfida", genre: "Thriller", year: 1995 },
  { title: "Collateral", genre: "Thriller", year: 2004 },
  { title: "Matrix", genre: "Fantascienza", year: 1999 },
  { title: "Blade Runner", genre: "Fantascienza", year: 1982 },
  { title: "2001: Odissea nello Spazio", genre: "Fantascienza", year: 1968 },
  { title: "Arrival", genre: "Fantascienza", year: 2016 },
  { title: "Minority Report", genre: "Fantascienza", year: 2002 },
  { title: "Alien", genre: "Fantascienza", year: 1979 },
  { title: "Aliens - Scontro Finale", genre: "Fantascienza", year: 1986 },
  { title: "Star Wars: Una Nuova Speranza", genre: "Fantascienza", year: 1977 },
  { title: "Star Wars: L’Impero Colpisce Ancora", genre: "Fantascienza", year: 1980 },
  { title: "Star Wars: Il Ritorno dello Jedi", genre: "Fantascienza", year: 1983 },
  { title: "Star Trek", genre: "Fantascienza", year: 1979 },
  { title: "The Martian", genre: "Fantascienza", year: 2015 },
  { title: "Dune", genre: "Fantascienza", year: 2021 },
  { title: "Ex Machina", genre: "Fantascienza", year: 2015 },
  { title: "Gattaca", genre: "Fantascienza", year: 1997 },
  { title: "Snowpiercer", genre: "Fantascienza", year: 2013 },
  { title: "Moon", genre: "Fantascienza", year: 2009 },
  { title: "Edge of Tomorrow", genre: "Fantascienza", year: 2014 },
  { title: "Ready Player One", genre: "Fantascienza", year: 2018 },
  { title: "The Shawshank Redemption", genre: "Drammatico", year: 1994 },
  { title: "The Godfather: Part II", genre: "Drammatico", year: 1974 },
  { title: "The Lord of the Rings: The Fellowship of the Ring", genre: "Azione", year: 2001 },
  { title: "The Lord of the Rings: The Two Towers", genre: "Azione", year: 2002 },
  { title: "The Lord of the Rings: The Return of the King", genre: "Azione", year: 2003 },
  { title: "The Dark Knight Rises", genre: "Azione", year: 2012 },
  { title: "The Revenant", genre: "Drammatico", year: 2015 },
  { title: "The Social Network", genre: "Drammatico", year: 2010 },
  { title: "The Pianist", genre: "Storico", year: 2002 },
  { title: "The Big Lebowski", genre: "Commedia", year: 1998 },
  { title: "The Truman Show", genre: "Drammatico", year: 1998 },
  { title: "The Great Escape", genre: "Azione", year: 1963 },
  { title: "The Bridge on the River Kwai", genre: "Storico", year: 1957 },
  { title: "The Maltese Falcon", genre: "Giallo", year: 1941 },
  { title: "The Treasure of the Sierra Madre", genre: "Avventura", year: 1948 },
  { title: "The Searchers", genre: "Western", year: 1956 },
  { title: "The Third Man", genre: "Thriller", year: 1949 },
  { title: "The Apartment", genre: "Commedia", year: 1960 },
  { title: "The Godfather: Part III", genre: "Drammatico", year: 1990 },
  { title: "The Great Dictator", genre: "Commedia", year: 1940 },
  { title: "The Big Sleep", genre: "Giallo", year: 1946 },
  { title: "The Killing", genre: "Giallo", year: 1956 },
  { title: "The Night of the Hunter", genre: "Thriller", year: 1955 },
  { title: "The Man Who Shot Liberty Valance", genre: "Western", year: 1962 },
  { title: "The Grapes of Wrath", genre: "Drammatico", year: 1940 },
  { title: "The Best Years of Our Lives", genre: "Drammatico", year: 1946 },
  { title: "The Big Parade", genre: "Storico", year: 1925 },
  { title: "The Birth of a Nation", genre: "Storico", year: 1915 },
  { title: "The Cabinet of Dr. Caligari", genre: "Horror", year: 1920 },
  { title: "The Phantom of the Opera", genre: "Horror", year: 1925 },
  { title: "The Hound of the Baskervilles", genre: "Giallo", year: 1939 },
  { title: "The Lady Vanishes", genre: "Thriller", year: 1938 },
  { title: "The 39 Steps", genre: "Thriller", year: 1935 },
  { title: "The Big Heat", genre: "Giallo", year: 1953 },
  { title: "The Big Knife", genre: "Drammatico", year: 1955 },
  { title: "The Big Combo", genre: "Giallo", year: 1955 },
  { title: "The Big Cat", genre: "Avventura", year: 1949 },
  { title: "The Big Boodle", genre: "Giallo", year: 1957 },
  { title: "The Big Bounce", genre: "Commedia", year: 2004 },
  { title: "The Big Chill", genre: "Commedia", year: 1983 },
  { title: "The Big Country", genre: "Western", year: 1958 },
  { title: "The Big Easy", genre: "Thriller", year: 1987 },
  { title: "The Big Hit", genre: "Azione", year: 1998 },
  { title: "La Vita è Bella", genre: "Drammatico", year: 1997 },
  { title: "Amélie", genre: "Romantico", year: 2001 },
  { title: "Slumdog Millionaire", genre: "Drammatico", year: 2008 },
  { title: "Birdman", genre: "Drammatico", year: 2014 },
  { title: "Spotlight", genre: "Drammatico", year: 2015 },
  { title: "Mad Max", genre: "Azione", year: 1979 },
  { title: "Blade Runner 2049", genre: "Fantascienza", year: 2017 },
  { title: "Guardians of the Galaxy Vol. 3", genre: "Azione", year: 2023 },
  { title: "Tenet", genre: "Fantascienza", year: 2020 },
  { title: "Dune: Part Two", genre: "Fantascienza", year: 2025 },
  { title: "Everything Everywhere All At Once", genre: "Fantascienza", year: 2022 },
  { title: "No Country for Old Men", genre: "Thriller", year: 2007 },
  { title: "There Will Be Blood", genre: "Drammatico", year: 2007 },
  { title: "A Beautiful Mind", genre: "Drammatico", year: 2001 },
  { title: "Glengarry Glen Ross", genre: "Drammatico", year: 1992 },
  { title: "The Imitation Game", genre: "Storico", year: 2014 },
  { title: "Spotlight", genre: "Drammatico", year: 2015 },
  { title: "Jojo Rabbit", genre: "Commedia", year: 2019 },
  { title: "1917", genre: "Storico", year: 2019 },
  { title: "Roma", genre: "Drammatico", year: 2018 },
  { title: "The Irishman", genre: "Drammatico", year: 2019 },
  { title: "Ford v Ferrari", genre: "Storico", year: 2019 },
  { title: "Soul", genre: "Animazione", year: 2020 },
  { title: "Luca", genre: "Animazione", year: 2021 },
  { title: "Encanto", genre: "Animazione", year: 2021 },
  { title: "Lightyear", genre: "Animazione", year: 2022 },
  { title: "Turning Red", genre: "Animazione", year: 2022 }
];



export default initialMovies;